import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
        <SessionProvider>
          <header className="sticky top-0 border-b mb-2 w-11/12 mx-auto rounded-2xl border-[#009688] bg-white/70  z-20">
            <Navbar></Navbar>
          </header>
          <main className="w-11/12 mx-auto">{children}</main>
          <footer className="border-t-2 border-[#009688]  w-full">
            <Footer />
          </footer>
        </SessionProvider>
      </body>
    </html>
  );
}
